
import React from 'react';
import { AlertTriangle, Shield } from 'lucide-react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-32 relative overflow-hidden">
      {/* Divine animated background layers */}
      <div className="absolute inset-0 bg-gradient-to-br from-purple-900/30 via-blue-900/30 to-pink-900/30 animate-pulse-glow"></div>
      <div className="absolute inset-0 bg-cyber-grid opacity-20 animate-float-slow"></div>
      
      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-20">
          <h2 className="text-5xl md:text-7xl font-orbitron font-bold mb-8 bg-gradient-to-r from-neon-blue via-neon-purple to-neon-pink bg-clip-text text-transparent animate-neon-pulse">
            Legal Disclaimer
          </h2>
          <div className="flex justify-center mt-6 space-x-4">
            <Shield className="text-neon-blue animate-pulse-glow" size={32} />
            <AlertTriangle className="text-neon-pink animate-pulse-glow" size={32} />
            <Shield className="text-neon-blue animate-pulse-glow" size={32} />
          </div>
        </div>
        
        <div className="max-w-5xl mx-auto glass-panel p-8 md:p-12 border-2 border-gradient-to-r from-neon-blue/50 via-neon-purple/50 to-neon-pink/50 rounded-2xl backdrop-blur-xl shadow-2xl">
          <div className="space-y-10 text-gray-200">
            <div className="p-6 bg-black/40 rounded-xl border border-neon-blue/30">
              <h3 className="text-2xl font-orbitron font-bold mb-4 text-neon-blue">Ownership and Intellectual Property</h3>
              <p className="leading-relaxed">Trivia Night GPT is powered by OpenAI's technology. The AI service provided is subject to OpenAI's Terms of Service and Privacy Policy. AI Web Tools LLC does not claim ownership of the underlying AI technology but provides access to this custom application.</p>
            </div>
            
            <div className="p-6 bg-black/40 rounded-xl border border-neon-purple/30">
              <h3 className="text-2xl font-orbitron font-bold mb-4 text-neon-purple">Content Accuracy</h3>
              <p className="leading-relaxed">While Trivia Night GPT strives to provide accurate and educational content, we cannot guarantee the complete accuracy of all trivia questions and answers. The content is generated by artificial intelligence and may occasionally contain errors or outdated information. Users should verify any critical information from reliable sources.</p>
            </div>
            
            <div className="p-6 bg-black/40 rounded-xl border border-neon-pink/30">
              <h3 className="text-2xl font-orbitron font-bold mb-4 text-neon-pink">User Conduct</h3>
              <p className="leading-relaxed">Users are responsible for their interactions with Trivia Night GPT and must comply with applicable laws and regulations. Inappropriate usage, attempts to manipulate the system, or generating harmful content are strictly prohibited.</p>
            </div>
            
            <div className="p-6 bg-black/40 rounded-xl border border-neon-yellow/30">
              <h3 className="text-2xl font-orbitron font-bold mb-4 text-neon-yellow">Age Appropriateness</h3>
              <p className="leading-relaxed">Trivia Night GPT is designed to be family-friendly, but parental supervision is recommended for younger users. Some content may not be suitable for all ages, and parents should review the categories and difficulty levels before allowing children to use the service.</p>
            </div>
            
            <div className="p-6 bg-black/40 rounded-xl border border-neon-green/30">
              <h3 className="text-2xl font-orbitron font-bold mb-4 text-neon-green">Limitation of Liability</h3>
              <p className="leading-relaxed">AI Web Tools LLC and its affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your access to or use of Trivia Night GPT. This includes, but is not limited to, any errors or inaccuracies in content, personal injury, property damage, or any loss of data.</p>
            </div>
            
            <div className="p-6 bg-black/40 rounded-xl border border-neon-blue/30">
              <h3 className="text-2xl font-orbitron font-bold mb-4 text-neon-blue">Changes to Terms</h3>
              <p className="leading-relaxed">We reserve the right to modify or replace these terms at any time. It is your responsibility to check for updates periodically. Continued use of Trivia Night GPT after changes constitutes acceptance of the new terms.</p>
            </div>
            
            <div className="p-6 bg-black/40 rounded-xl border border-neon-purple/30">
              <h3 className="text-2xl font-orbitron font-bold mb-4 text-neon-purple">Contact Information</h3>
              <p className="leading-relaxed">For questions regarding these terms or the service, please contact us at <a href="mailto:Contact@ai-webtools.com" className="text-neon-blue hover:text-neon-purple transition-colors duration-300">Contact@ai-webtools.com</a> or call <a href="tel:+14758008096" className="text-neon-blue hover:text-neon-purple transition-colors duration-300">(475) 800-8096</a>.</p>
            </div>
          </div>
          
          <div className="mt-12 pt-8 border-t border-gradient-to-r from-neon-blue/30 via-neon-purple/30 to-neon-pink/30 text-center">
            <p className="text-gray-300 text-sm mb-8 leading-relaxed">By accessing or using Trivia Night GPT, you acknowledge that you have read, understood, and agree to be bound by these terms and conditions.</p>
            
            <div className="flex flex-wrap justify-center gap-6">
              <a 
                href="https://openai.com/policies/privacy-policy/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="px-6 py-3 bg-gradient-to-r from-neon-blue/30 to-neon-purple/30 rounded-full border border-neon-blue/50 text-neon-blue hover:text-white hover:from-neon-blue/50 hover:to-neon-purple/50 transition-all duration-300 transform hover:scale-105"
              >
                Privacy Policy
              </a>
              <span className="text-gray-500 self-center">|</span>
              <a 
                href="https://aiwebtools.lovable.app/disclaimers" 
                target="_blank" 
                rel="noopener noreferrer"
                className="px-6 py-3 bg-gradient-to-r from-neon-purple/30 to-neon-pink/30 rounded-full border border-neon-purple/50 text-neon-purple hover:text-white hover:from-neon-purple/50 hover:to-neon-pink/50 transition-all duration-300 transform hover:scale-105"
              >
                Terms of Service
              </a>
            </div>
          </div>
        </div>
      </div>
      
      {/* Divine floating elements */}
      <div className="absolute top-1/4 right-1/4 w-1/3 h-1/3 bg-neon-yellow/5 rounded-full blur-3xl animate-float"></div>
      <div className="absolute bottom-1/4 left-1/4 w-1/4 h-1/4 bg-neon-pink/5 rounded-full blur-2xl animate-float-delay-1"></div>
      <div className="absolute top-1/2 right-1/6 w-1/5 h-1/5 bg-neon-green/5 rounded-full blur-xl animate-float-delay-2"></div>
    </section>
  );
};

export default Disclaimer;
