
import React from 'react';
import { AlertTriangle, Shield } from 'lucide-react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-20 relative">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="section-title">Legal Disclaimer</h2>
          <div className="flex justify-center mt-4">
            <Shield className="text-neon-blue mx-1" size={24} />
            <AlertTriangle className="text-neon-pink mx-1" size={24} />
            <Shield className="text-neon-blue mx-1" size={24} />
          </div>
        </div>
        
        <div className="max-w-4xl mx-auto glass-panel p-6 md:p-8 border border-white/10">
          <div className="space-y-6 text-gray-300">
            <div>
              <h3 className="text-xl font-orbitron font-bold mb-3 text-white">Ownership and Intellectual Property</h3>
              <p>Trivia Night GPT is powered by OpenAI's technology. The AI service provided is subject to OpenAI's Terms of Service and Privacy Policy. AI Web Tools LLC does not claim ownership of the underlying AI technology but provides access to this custom application.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-orbitron font-bold mb-3 text-white">Content Accuracy</h3>
              <p>While Trivia Night GPT strives to provide accurate and educational content, we cannot guarantee the complete accuracy of all trivia questions and answers. The content is generated by artificial intelligence and may occasionally contain errors or outdated information. Users should verify any critical information from reliable sources.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-orbitron font-bold mb-3 text-white">User Conduct</h3>
              <p>Users are responsible for their interactions with Trivia Night GPT and must comply with applicable laws and regulations. Inappropriate usage, attempts to manipulate the system, or generating harmful content are strictly prohibited.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-orbitron font-bold mb-3 text-white">Age Appropriateness</h3>
              <p>Trivia Night GPT is designed to be family-friendly, but parental supervision is recommended for younger users. Some content may not be suitable for all ages, and parents should review the categories and difficulty levels before allowing children to use the service.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-orbitron font-bold mb-3 text-white">Limitation of Liability</h3>
              <p>AI Web Tools LLC and its affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your access to or use of Trivia Night GPT. This includes, but is not limited to, any errors or inaccuracies in content, personal injury, property damage, or any loss of data.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-orbitron font-bold mb-3 text-white">Changes to Terms</h3>
              <p>We reserve the right to modify or replace these terms at any time. It is your responsibility to check for updates periodically. Continued use of Trivia Night GPT after changes constitutes acceptance of the new terms.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-orbitron font-bold mb-3 text-white">Contact Information</h3>
              <p>For questions regarding these terms or the service, please contact us at <a href="mailto:Contact@ai-webtools.com" className="text-neon-blue hover:text-neon-purple transition-colors">Contact@ai-webtools.com</a> or call <a href="tel:+14758008096" className="text-neon-blue hover:text-neon-purple transition-colors">(475) 800-8096</a>.</p>
            </div>
          </div>
          
          <div className="mt-8 pt-8 border-t border-white/10 text-center">
            <p className="text-gray-400 text-sm">By accessing or using Trivia Night GPT, you acknowledge that you have read, understood, and agree to be bound by these terms and conditions.</p>
            
            <div className="mt-6 flex flex-wrap justify-center gap-4">
              <a 
                href="https://openai.com/policies/privacy-policy/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-neon-blue hover:text-neon-purple transition-colors text-sm"
              >
                Privacy Policy
              </a>
              <span className="text-gray-500">|</span>
              <a 
                href="https://aiwebtools.ai/terms-of-services" 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-neon-blue hover:text-neon-purple transition-colors text-sm"
              >
                Terms of Service
              </a>
            </div>
          </div>
        </div>
      </div>
      
      {/* Decorative element */}
      <div className="absolute top-1/4 right-1/4 w-1/3 h-1/3 bg-neon-yellow/5 rounded-full blur-3xl"></div>
    </section>
  );
};

export default Disclaimer;
